


import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author romi
 */
public class DisplaySyllabus extends javax.swing.JFrame {

    /**
     * Creates new form DisplaySyllabus
     */
       DefaultTableModel model;
    public DisplaySyllabus() {
        initComponents();
     Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        currentDate();
    
    }
    
    public void currentDate (){
        
        Calendar cal =new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        date_lbl.setText((month+1)+"/"+day+"/"+year);
        int hour=cal.get(Calendar.HOUR);
        int minute=cal.get(Calendar.MINUTE);
        int second=cal.get(Calendar.SECOND);
        time_lbl.setText(+hour+":"+minute+":"+second);
        }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        displaypannel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        sem = new javax.swing.JLabel();
        inSem2 = new javax.swing.JComboBox<>();
        submit = new javax.swing.JButton();
        mainmenu = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tablepannel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        opTable3 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        Date_time = new javax.swing.JMenuBar();
        date_lbl = new javax.swing.JMenu();
        time_lbl = new javax.swing.JMenu();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/361223.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 505));
        setUndecorated(true);
        getContentPane().setLayout(null);

        displaypannel.setLayout(null);

        title.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        title.setText("             Display Syllabus");
        displaypannel.add(title);
        title.setBounds(-60, 10, 440, 50);

        sem.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        sem.setForeground(new java.awt.Color(153, 255, 0));
        sem.setText("Select semester:");
        displaypannel.add(sem);
        sem.setBounds(20, 100, 180, 28);

        inSem2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", " " }));
        displaypannel.add(inSem2);
        inSem2.setBounds(200, 100, 40, 30);

        submit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        displaypannel.add(submit);
        submit.setBounds(200, 150, 100, 25);

        mainmenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mainmenu.setText("Back");
        mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuActionPerformed(evt);
            }
        });
        displaypannel.add(mainmenu);
        mainmenu.setBounds(60, 230, 100, 25);

        exit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        displaypannel.add(exit);
        exit.setBounds(210, 390, 60, 25);

        logout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        displaypannel.add(logout);
        logout.setBounds(60, 390, 100, 25);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/361223.jpg"))); // NOI18N
        displaypannel.add(jLabel2);
        jLabel2.setBounds(0, 0, 1140, 650);

        getContentPane().add(displaypannel);
        displaypannel.setBounds(0, 0, 360, 580);

        tablepannel.setLayout(null);

        opTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sem", "Subject code", "Subject Name", "Syllabus", "Textbook"
            }
        ));
        jScrollPane3.setViewportView(opTable3);

        tablepannel.add(jScrollPane3);
        jScrollPane3.setBounds(30, 20, 560, 420);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        tablepannel.add(jSeparator1);
        jSeparator1.setBounds(10, 0, 20, 680);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/361223.jpg"))); // NOI18N
        tablepannel.add(jLabel3);
        jLabel3.setBounds(-640, 0, 1430, 690);

        getContentPane().add(tablepannel);
        tablepannel.setBounds(350, 0, 610, 600);

        date_lbl.setText("Date");
        Date_time.add(date_lbl);

        time_lbl.setText("Time");
        Date_time.add(time_lbl);

        setJMenuBar(Date_time);

        pack();
    }// </editor-fold>//GEN-END:initComponents
             public void close()
    {
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
 
    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

        model=(DefaultTableModel)opTable3.getModel();
        
        try{
        
            model.setRowCount(0);
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/prashant?zeroDateTimeBehavior=convertToNull","root","");
            Statement stmt=con.createStatement();

            ResultSet rs=stmt.executeQuery("select * from `subdetails` WHERE SEM='"+inSem2.getSelectedItem()+"'");
            if(rs.next()){
                  
            addrow();
            }
            else{
                  JOptionPane.showMessageDialog(null, "Not found !","Error message", JOptionPane.INFORMATION_MESSAGE);
            }
        }catch(ClassNotFoundException | SQLException e){
            System.out.println(e); 
                              JOptionPane.showMessageDialog(null, "Not found !","Error message", JOptionPane.INFORMATION_MESSAGE);
        }

        
    }//GEN-LAST:event_submitActionPerformed
public void addrow(){
    try{
        model=(DefaultTableModel)opTable3.getModel();
Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/prashant?zeroDateTimeBehavior=convertToNull","root","");
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select * from `subdetails` WHERE SEM='"+inSem2.getSelectedItem()+"'");
    String rg[]=new String[5];
            while(rs.next()) {
                rg[0]=(String)inSem2.getSelectedItem();
                rg[1]=rs.getString(2);
                rg[2]=rs.getString(3);
                rg[3]=rs.getString(4);
                rg[4]=rs.getString(5);

                model.addRow(rg);
            }
              }catch(ClassNotFoundException | SQLException e){
            System.out.println(e);
                              JOptionPane.showMessageDialog(null, "Not found !","Error message", JOptionPane.INFORMATION_MESSAGE);
        }
  
}
    private void mainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuActionPerformed
        close();
        new MainMenu().setVisible(true);   
        
        
    }//GEN-LAST:event_mainmenuActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        close();
        new loginMenu().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplaySyllabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplaySyllabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplaySyllabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplaySyllabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplaySyllabus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Date_time;
    private javax.swing.JMenu date_lbl;
    private javax.swing.JPanel displaypannel;
    private javax.swing.JButton exit;
    private javax.swing.JComboBox<String> inSem2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logout;
    private javax.swing.JButton mainmenu;
    private javax.swing.JTable opTable3;
    private javax.swing.JLabel sem;
    private javax.swing.JButton submit;
    private javax.swing.JPanel tablepannel;
    private javax.swing.JMenu time_lbl;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
