import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class loginMenu extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form loginMenu
     */
    Timer time;
    public loginMenu() {
        initComponents();
         
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        currentDate();
    time=new Timer(10,this);
    }
    
    public void currentDate (){
        
        Calendar cal =new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        date_lbl.setText((month+1)+"/"+day+"/"+year);
        int hour=cal.get(Calendar.HOUR);
        int minute=cal.get(Calendar.MINUTE);
        int second=cal.get(Calendar.SECOND);
        time_lbl.setText(+hour+":"+minute+":"+second);
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        inUser = new javax.swing.JTextField();
        inPass = new javax.swing.JPasswordField();
        inReset = new javax.swing.JButton();
        inLogin = new javax.swing.JButton();
        outExit = new javax.swing.JButton();
        progress = new javax.swing.JProgressBar();
        background = new javax.swing.JLabel();
        Date_time = new javax.swing.JMenuBar();
        date_lbl = new javax.swing.JMenu();
        time_lbl = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setName("loginframe"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 400));
        getContentPane().setLayout(null);

        password.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password :");
        password.setMaximumSize(new java.awt.Dimension(95, 25));
        password.setMinimumSize(new java.awt.Dimension(95, 25));
        password.setPreferredSize(new java.awt.Dimension(95, 25));
        getContentPane().add(password);
        password.setBounds(190, 320, 120, 40);

        user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("Username :");
        getContentPane().add(user);
        user.setBounds(190, 270, 120, 40);

        inUser.setMaximumSize(new java.awt.Dimension(95, 25));
        inUser.setMinimumSize(new java.awt.Dimension(95, 25));
        inUser.setPreferredSize(new java.awt.Dimension(95, 25));
        getContentPane().add(inUser);
        inUser.setBounds(330, 280, 150, 25);

        inPass.setMaximumSize(new java.awt.Dimension(95, 25));
        inPass.setMinimumSize(new java.awt.Dimension(95, 25));
        inPass.setPreferredSize(new java.awt.Dimension(95, 25));
        getContentPane().add(inPass);
        inPass.setBounds(330, 330, 150, 25);

        inReset.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        inReset.setText("Reset");
        inReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inResetActionPerformed(evt);
            }
        });
        getContentPane().add(inReset);
        inReset.setBounds(430, 390, 71, 25);

        inLogin.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        inLogin.setText("Login");
        inLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inLoginActionPerformed(evt);
            }
        });
        getContentPane().add(inLogin);
        inLogin.setBounds(330, 390, 70, 25);

        outExit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        outExit.setText("Exit");
        outExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outExitActionPerformed(evt);
            }
        });
        getContentPane().add(outExit);
        outExit.setBounds(700, 30, 79, 25);
        getContentPane().add(progress);
        progress.setBounds(150, 450, 510, 14);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/floor_minimalistic_pattern_wood_patterns_wood_panels_wood_texture_simplistic_1920x1080_wallpaper_Wallpaper HD_2560x1440_www.paperhi.com.jpg"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(800, 600));
        background.setMinimumSize(new java.awt.Dimension(800, 600));
        background.setPreferredSize(new java.awt.Dimension(800, 800));
        getContentPane().add(background);
        background.setBounds(0, -60, 910, 670);

        date_lbl.setText("Date");
        Date_time.add(date_lbl);

        time_lbl.setText("Time");
        Date_time.add(time_lbl);

        setJMenuBar(Date_time);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inLoginActionPerformed

          if(inUser.getText().equals("admin") && inPass.getText().equals("admin"))
       {
           time.start();
       }
       else
           JOptionPane.showMessageDialog(this, "LOGIN UNSUCESSFULL");

    }//GEN-LAST:event_inLoginActionPerformed
   public void close()
    {
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    
    
    
    
    private void inResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inResetActionPerformed

             inUser.setText("");
             inPass.setText("");


        // TODO add your handling code here:
    }//GEN-LAST:event_inResetActionPerformed

    private void outExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outExitActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_outExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Date_time;
    private javax.swing.JLabel background;
    private javax.swing.JMenu date_lbl;
    private javax.swing.JButton inLogin;
    private javax.swing.JPasswordField inPass;
    private javax.swing.JButton inReset;
    private javax.swing.JTextField inUser;
    private javax.swing.JButton outExit;
    private javax.swing.JLabel password;
    private javax.swing.JProgressBar progress;
    private javax.swing.JMenu time_lbl;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        int n=progress.getValue();
        
        if(n!=100)
            progress.setValue(++n);
        else
        {
            time.stop();
            new MainMenu().setVisible(true);
            this.dispose();
        }
        
        
        
    }
}
