
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author romi
 */
public class SearchSyllabus extends javax.swing.JFrame {

    /**
     * Creates new form SearchSyllabus
     */
      DefaultTableModel model;
    public SearchSyllabus() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        currentDate();
    
    }
    
    public void currentDate (){
        
        Calendar cal =new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        date_lbl.setText((month+1)+"/"+day+"/"+year);
        int hour=cal.get(Calendar.HOUR);
        int minute=cal.get(Calendar.MINUTE);
        int second=cal.get(Calendar.SECOND);
        time_lbl.setText(+hour+":"+minute+":"+second);
        }
    
     public void close()
    {
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        table = new javax.swing.JScrollPane();
        opTable2 = new javax.swing.JTable();
        logout = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        sem = new javax.swing.JLabel();
        sem1 = new javax.swing.JLabel();
        sem3 = new javax.swing.JLabel();
        Semradio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inSem4 = new javax.swing.JComboBox<>();
        inBook4 = new javax.swing.JTextField();
        inCode4 = new javax.swing.JTextField();
        jButton23 = new javax.swing.JButton();
        mainmenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        Date_time = new javax.swing.JMenuBar();
        date_lbl = new javax.swing.JMenu();
        time_lbl = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1062, 655));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        title.setBackground(new java.awt.Color(0, 0, 0));
        title.setFont(new java.awt.Font("Poor Richard", 1, 38)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 204));
        title.setText("            Search Syllabus");
        jPanel1.add(title);
        title.setBounds(30, 10, 440, 50);

        opTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sem", "Subject code", "Subject Name", "Syllabus", "Textbook"
            }
        ));
        table.setViewportView(opTable2);

        jPanel1.add(table);
        table.setBounds(490, 30, 530, 430);

        logout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout);
        logout.setBounds(330, 540, 100, 25);

        exit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(940, 540, 60, 25);

        sem.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        sem.setForeground(new java.awt.Color(255, 255, 204));
        sem.setText("Textbook : ");
        jPanel1.add(sem);
        sem.setBounds(70, 210, 130, 40);

        sem1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        sem1.setForeground(new java.awt.Color(255, 255, 204));
        sem1.setText("SEARCH BY:");
        jPanel1.add(sem1);
        sem1.setBounds(70, 90, 130, 30);

        sem3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        sem3.setForeground(new java.awt.Color(255, 255, 204));
        sem3.setText("Subject code :");
        jPanel1.add(sem3);
        sem3.setBounds(70, 150, 130, 30);

        Semradio.setBackground(new java.awt.Color(204, 204, 0));
        Semradio.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        Semradio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SemradioActionPerformed(evt);
            }
        });
        jPanel1.add(Semradio);
        Semradio.setBounds(170, 280, 20, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 204));
        jLabel1.setText("-or-");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 250, 41, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("-or-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 190, 41, 17);

        inSem4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", " " }));
        inSem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inSem4ActionPerformed(evt);
            }
        });
        jPanel1.add(inSem4);
        inSem4.setBounds(210, 280, 50, 30);
        jPanel1.add(inBook4);
        inBook4.setBounds(210, 220, 180, 30);
        jPanel1.add(inCode4);
        inCode4.setBounds(210, 152, 180, 30);

        jButton23.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton23.setText("Submit");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton23);
        jButton23.setBounds(210, 340, 80, 25);

        mainmenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mainmenu.setText("Back");
        mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuActionPerformed(evt);
            }
        });
        jPanel1.add(mainmenu);
        mainmenu.setBounds(110, 540, 120, 25);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("Semester :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 280, 100, 30);

        reset.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(320, 340, 70, 25);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bkmgmt.jpg"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 1070, 640);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1070, 630);

        date_lbl.setText("Date");
        Date_time.add(date_lbl);

        time_lbl.setText("Time");
        Date_time.add(time_lbl);

        setJMenuBar(Date_time);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed

        System.exit(0);        // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        close();
        new loginMenu().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void SemradioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SemradioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SemradioActionPerformed

    private void inSem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inSem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inSem4ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed

        model=(DefaultTableModel)opTable2.getModel();

        model.setRowCount(0);

        String book=inBook4.getText();
        String code=inCode4.getText();



        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/prashant?zeroDateTimeBehavior=convertToNull","root","");
            Statement stmt=con.createStatement();
            String row[]=new String[5];

            if(Semradio.isSelected()){

                ResultSet rs=stmt.executeQuery("select * from `subdetails` where SEM='"+inSem4.getSelectedItem()+"'");
                if(rs.next()){
                    addrow();
                }
                else{
                    JOptionPane.showMessageDialog(null, "Not found !","Error message", JOptionPane.INFORMATION_MESSAGE);
                   
                }

            }

            else{
                
                    try {
                        ResultSet rs=stmt.executeQuery("select * from `subdetails` WHERE TEXTBOOK='"+book+"' OR `SUBJECT CODE`='"+code+"'");

                        while(rs.next())
                        {
                            row[0]=rs.getString(1);
                            row[1]=rs.getString(2);
                            row[2]=rs.getString(3);
                            row[3]=rs.getString(4);
                            row[4]=rs.getString(5);
                            model.addRow(row);
                          //  j++;

                        }
                        rs.close();

                    } catch (SQLException ex){System.out.println(ex);
                    JOptionPane.showMessageDialog(null, "Not found !","Error message", JOptionPane.INFORMATION_MESSAGE);
                    }

                    

                }

            

        }catch(ClassNotFoundException | SQLException e){System.out.println(e);
        JOptionPane.showMessageDialog(null, "Not found !","Error message", JOptionPane.INFORMATION_MESSAGE);
        }
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton23ActionPerformed
public void addrow(){
    model=(DefaultTableModel)opTable2.getModel();

        model.setRowCount(0);
    try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/prashant?zeroDateTimeBehavior=convertToNull","root","");
            Statement stmt=con.createStatement();
            String row[]=new String[5];
             ResultSet rs=stmt.executeQuery("select * from `subdetails` where SEM='"+inSem4.getSelectedItem()+"'");
             while(rs.next()) {
                    row[0]=(String)inSem4.getSelectedItem();
                    row[1]=rs.getString(2);
                    row[2]=rs.getString(3);
                    row[3]=rs.getString(4);
                    row[4]=rs.getString(5);

                    model.addRow(row);
             }
            }catch(ClassNotFoundException | SQLException e){System.out.println(e);
        JOptionPane.showMessageDialog(null, "Not found !","Error message", JOptionPane.INFORMATION_MESSAGE);
        }
}
    private void mainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuActionPerformed
        close();
        new MainMenu().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_mainmenuActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed

        inCode4.setText("");
        inBook4.setText("");


        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchSyllabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchSyllabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchSyllabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchSyllabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchSyllabus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Date_time;
    private javax.swing.JRadioButton Semradio;
    private javax.swing.JLabel background;
    private javax.swing.JMenu date_lbl;
    private javax.swing.JButton exit;
    private javax.swing.JTextField inBook4;
    private javax.swing.JTextField inCode4;
    private javax.swing.JComboBox<String> inSem4;
    private javax.swing.JButton jButton23;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton mainmenu;
    private javax.swing.JTable opTable2;
    private javax.swing.JButton reset;
    private javax.swing.JLabel sem;
    private javax.swing.JLabel sem1;
    private javax.swing.JLabel sem3;
    private javax.swing.JScrollPane table;
    private javax.swing.JMenu time_lbl;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
