
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author romi
 */
public class UpdateSyllabus extends javax.swing.JFrame {

    /**
     * Creates new form UpdateSyllabus
     */
    DefaultTableModel model;
    public UpdateSyllabus() {
        initComponents();
         model =(DefaultTableModel)opTable.getModel();

               Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        currentDate();
    
    }
    
    public void currentDate (){
        
        Calendar cal =new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        date_lbl.setText((month+1)+"/"+day+"/"+year);
        int hour=cal.get(Calendar.HOUR);
        int minute=cal.get(Calendar.MINUTE);
        int second=cal.get(Calendar.SECOND);
        time_lbl.setText(+hour+":"+minute+":"+second);
        }
    
     public void close()
    {
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updatepannel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        sem = new javax.swing.JLabel();
        subjectcode = new javax.swing.JLabel();
        oldsyllabus = new javax.swing.JLabel();
        newsyllabus = new javax.swing.JLabel();
        inSem1 = new javax.swing.JComboBox<>();
        inCode1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        inOld = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        inNew = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        mainmenu = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tablepannel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        opTable = new javax.swing.JTable();
        Date_time = new javax.swing.JMenuBar();
        date_lbl = new javax.swing.JMenu();
        time_lbl = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1220, 680));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1220, 680));
        getContentPane().setLayout(null);

        updatepannel.setBackground(new java.awt.Color(204, 204, 255));
        updatepannel.setLayout(null);

        title.setFont(new java.awt.Font("Poor Richard", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(240, 240, 240));
        title.setText("            Update Syllabus");
        updatepannel.add(title);
        title.setBounds(100, 10, 440, 50);

        sem.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        sem.setForeground(new java.awt.Color(255, 255, 255));
        sem.setText("Sem:");
        updatepannel.add(sem);
        sem.setBounds(60, 100, 39, 22);

        subjectcode.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        subjectcode.setForeground(new java.awt.Color(255, 255, 255));
        subjectcode.setText("Subject Code:");
        updatepannel.add(subjectcode);
        subjectcode.setBounds(60, 140, 104, 22);

        oldsyllabus.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        oldsyllabus.setForeground(new java.awt.Color(255, 255, 255));
        oldsyllabus.setText("Old Syllabus:");
        updatepannel.add(oldsyllabus);
        oldsyllabus.setBounds(60, 190, 120, 22);

        newsyllabus.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        newsyllabus.setForeground(new java.awt.Color(255, 255, 255));
        newsyllabus.setText("New Syllabus:");
        updatepannel.add(newsyllabus);
        newsyllabus.setBounds(60, 340, 108, 22);

        inSem1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        inSem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inSem1ActionPerformed(evt);
            }
        });
        updatepannel.add(inSem1);
        inSem1.setBounds(210, 100, 40, 22);

        inCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inCode1ActionPerformed(evt);
            }
        });
        updatepannel.add(inCode1);
        inCode1.setBounds(210, 140, 190, 30);

        inOld.setColumns(20);
        inOld.setRows(5);
        jScrollPane2.setViewportView(inOld);

        updatepannel.add(jScrollPane2);
        jScrollPane2.setBounds(210, 190, 400, 130);

        inNew.setColumns(20);
        inNew.setRows(5);
        jScrollPane3.setViewportView(inNew);

        updatepannel.add(jScrollPane3);
        jScrollPane3.setBounds(210, 340, 400, 130);

        submit.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        updatepannel.add(submit);
        submit.setBounds(210, 490, 80, 25);

        reset.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        updatepannel.add(reset);
        reset.setBounds(320, 490, 70, 25);

        mainmenu.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        mainmenu.setText("Back");
        mainmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuActionPerformed(evt);
            }
        });
        updatepannel.add(mainmenu);
        mainmenu.setBounds(210, 580, 110, 25);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        updatepannel.add(jButton4);
        jButton4.setBounds(460, 580, 60, 25);

        logout.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        updatepannel.add(logout);
        logout.setBounds(340, 580, 100, 25);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds-assasins-blood-images-style-background.jpg"))); // NOI18N
        updatepannel.add(background);
        background.setBounds(-150, -20, 1290, 700);

        getContentPane().add(updatepannel);
        updatepannel.setBounds(0, 0, 640, 660);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(640, -10, 20, 680);

        tablepannel.setBackground(new java.awt.Color(255, 204, 204));

        opTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sem", "Subject code", "Old Syllabus", "New Syllabus"
            }
        ));
        jScrollPane1.setViewportView(opTable);

        javax.swing.GroupLayout tablepannelLayout = new javax.swing.GroupLayout(tablepannel);
        tablepannel.setLayout(tablepannelLayout);
        tablepannelLayout.setHorizontalGroup(
            tablepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablepannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        tablepannelLayout.setVerticalGroup(
            tablepannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tablepannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        getContentPane().add(tablepannel);
        tablepannel.setBounds(640, 0, 600, 670);

        date_lbl.setText("Date");
        Date_time.add(date_lbl);

        time_lbl.setText("Time");
        Date_time.add(time_lbl);

        setJMenuBar(Date_time);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inCode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inCode1ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
      
                if(inCode1.getText().isEmpty())
                { 
                    JOptionPane.showMessageDialog(null, "Subject Code Missing", "Error Message", JOptionPane.WARNING_MESSAGE);
                }
                else if(inOld.getText().isEmpty())             
                {
                    JOptionPane.showMessageDialog(null, "Old Syllabus Missing", "Error Message", JOptionPane.WARNING_MESSAGE);
                }
               else if(inNew.getText().isEmpty())             
                {
                    JOptionPane.showMessageDialog(null, "New Syllabus Missing", "Error Message", JOptionPane.WARNING_MESSAGE);
                }

        else
          {
                try{
      Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/prashant?zeroDateTimeBehavior=convertToNull","root","");
            Statement stmt=con.createStatement();
           ResultSet rs=stmt.executeQuery("select * from `subdetails` where (`SUBJECT CODE` = '"+inCode1.getText()+"' AND SYLLABUS ='"+inOld.getText()+"')");
           if(rs.next()&&!inNew.getText().isEmpty()){
               execute();
           }
           else{
               JOptionPane.showMessageDialog(null, "Invalid","Error message", JOptionPane.INFORMATION_MESSAGE);
           }
      
   

        
         }catch(ClassNotFoundException | SQLException e){

            System.out.println(e); }
        
        
        
        
          }   
        
       
        // TODO add your handling code here:
    }                   
    
    public void execute(){
        model=(DefaultTableModel)opTable.getModel();
  String rg[]=new String[4];
        try{
      Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/prashant?zeroDateTimeBehavior=convertToNull","root","");
            Statement stmt=con.createStatement();
           ResultSet rs=stmt.executeQuery("select * from `subdetails` where `SUBJECT CODE` = '"+inCode1.getText()+"'");
           while(rs.next())
           {
               rg[2]=rs.getString(4);
           }
           rs.close();
           stmt.executeUpdate("update `subdetails` set SYLLABUS = '"+inNew.getText()+"' where SYLLABUS ='"+inOld.getText()+"'");
           rs=stmt.executeQuery("select * from `subdetails` where `SUBJECT CODE` = '"+inCode1.getText()+"'");
           while(rs.next()){
               rg[0]=rs.getString(1);
               rg[1]=rs.getString(2);
               rg[3]=rs.getString(4);
               model.addRow(rg);
           }
           }catch(ClassNotFoundException | SQLException e){

            System.out.println(e); }
        
    }

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          

         model=(DefaultTableModel)opTable.getModel();
        try{
            model.setRowCount(0);
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/prashant?zeroDateTimeBehavior=convertToNull","root","");
            Statement stmt=con.createStatement();
        
           
            ResultSet rs=stmt.executeQuery("select * from `subdetails`");  

            
            String rg[]=new String[5];
                        while(rs.next()) {
                            rg[0]=(String)inSem1.getSelectedItem();
                        rg[1]=rs.getString(1);
                        rg[2]=rs.getString(2);
                        rg[3]=rs.getString(3);
                        rg[4]=rs.getString(4);

                            model.addRow(rg);
                        }
        
        }catch(ClassNotFoundException | SQLException e){

            System.out.println(e); 
                          JOptionPane.showMessageDialog(null, "Not found !","Error message", JOptionPane.INFORMATION_MESSAGE);
        }

        
    
    }//GEN-LAST:event_submitActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed

        inCode1.setText("");
        inOld.setText("");
        inNew.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void mainmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuActionPerformed
         close();
        new MainMenu().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_mainmenuActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        System.exit(0);                   // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        
        close();
        new loginMenu().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_logoutActionPerformed

    private void inSem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inSem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inSem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateSyllabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateSyllabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateSyllabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateSyllabus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateSyllabus().setVisible(true);
            }
        });
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Date_time;
    private javax.swing.JLabel background;
    private javax.swing.JMenu date_lbl;
    private javax.swing.JTextField inCode1;
    private javax.swing.JTextArea inNew;
    private javax.swing.JTextArea inOld;
    private javax.swing.JComboBox<String> inSem1;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logout;
    private javax.swing.JButton mainmenu;
    private javax.swing.JLabel newsyllabus;
    private javax.swing.JLabel oldsyllabus;
    private javax.swing.JTable opTable;
    private javax.swing.JButton reset;
    private javax.swing.JLabel sem;
    private javax.swing.JLabel subjectcode;
    private javax.swing.JButton submit;
    private javax.swing.JPanel tablepannel;
    private javax.swing.JMenu time_lbl;
    private javax.swing.JLabel title;
    private javax.swing.JPanel updatepannel;
    // End of variables declaration//GEN-END:variables
}
